In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

df = pd.read_csv("crx.csv")
df.sample(5)

    A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14   A15  T
420  b  35.00   2.50  u  g  i  v  1.00  f   f    0   t   g  00210     0  -
139  a  26.92  13.50  u  g  q  h  5.00  t   t    2   f   g  00000  5000  +
526  b  41.58   1.75  u  g  k  v  0.21  t   f    0   f   g  00160     0  -
340  a  39.08   4.00  u  g  c  v  3.00  f   f    0   f   g  00480     0  -
83   a      ?   3.50  u  g  d  v  3.00  t   f    0   t   g  00300     0  -

In [3]:
df.drop('A14', axis=1, inplace=True)
df.drop('A11', axis=1, inplace=True)

df.sample(5)

    A1     A2    A3 A4 A5  A6  A7      A8 A9 A10 A12 A13   A15  T
91   b  31.42  15.5  u  g   c   v   0.500  t   f   f   g     0  -
27   b  56.58  18.5  u  g   d  bb  15.000  t   t   t   g     0  +
653  b  21.50  11.5  u  g   i   v   0.500  t   f   t   g    68  -
583  b  32.67   9.0  y  p   w   h   5.250  t   f   t   g     0  +
590  b  30.17   6.5  u  g  cc   v   3.125  t   t   f   g  1200  +

In [4]:
df1 = df[(df.A1 != '?') & (df.A2 != '?') & (df.A4 != '?') & (df.A5 != '?') & (df.A6 != '?') & (df.A7 != '?')]
df1.A2 = pd.to_numeric(df1.A2)

C:\Users\ashan_105579\Anaconda3\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [5]:
df1['A1'].replace({'a': 1,'b': 0},inplace=True)
df1['A9'].replace({'t': 1,'f': 0},inplace=True)
df1['A10'].replace({'t': 1,'f': 0},inplace=True)
df1['A12'].replace({'t': 1,'f': 0},inplace=True)
df1['T'].replace({'+': 1,'-': 0},inplace=True)

C:\Users\ashan_105579\Anaconda3\lib\site-packages\pandas\core\series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [6]:
df1.sample(6)

     A1     A2      A3 A4 A5  A6 A7     A8  A9  A10  A12 A13   A15  T
529   0  43.25  25.210  u  g   q  h  0.210   1    1    0   g    90  0
491   0  24.17   0.875  u  g   q  v  4.625   1    1    1   g  2000  1
47    0  31.92   4.460  u  g  cc  h  6.040   1    1    0   g   300  1
14    1  45.83  10.500  u  g   q  v  5.000   1    1    1   g     0  1
425   0  24.58   1.250  u  g   c  v  0.250   0    0    0   g     0  0
411   0  25.17   3.000  u  g   c  v  1.250   0    1    0   g    22  0

In [7]:
df2 = pd.get_dummies(data=df1, columns=['A4','A5', 'A6', 'A7', 'A13'])

In [8]:
df2.sample(5)

,A1,A2,A3,A8,A9,A10,A12,A15,T,A4_l,...,A7_ff,A7_h,A7_j,A7_n,A7_o,A7_v,A7_z,A13_g,A13_p,A13_s
278,0,24.58,13.500,0.000,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
149,1,52.83,15.000,5.500,1,1,0,2200,1,0,...,0,0,0,0,0,1,0,1,0,0
356,0,41.17,1.335,0.165,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
159,0,34.08,0.080,0.040,1,1,1,2000,1,0,...,0,0,0,0,0,0,0,1,0,0
570,0,59.50,2.750,1.750,1,1,1,58,1,0,...,0,0,0,0,0,1,0,1,0,0

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
df2[df2.columns] = scaler.fit_transform(df2[df2.columns])
print("done")

done

In [10]:
df2.sample(5)

,A1,A2,A3,A8,A9,A10,A12,A15,T,A4_l,...,A7_ff,A7_h,A7_j,A7_n,A7_o,A7_v,A7_z,A13_g,A13_p,A13_s
514,0.0,0.141587,0.090714,0.090702,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
211,0.0,0.167937,0.236607,0.192982,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
81,1.0,0.220952,0.053571,0.070175,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
91,0.0,0.280476,0.553571,0.017544,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
665,0.0,0.286984,0.001429,0.001404,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [11]:
X = df2.drop('T',axis='columns')
y = df2['T']

In [12]:
X.shape[1]

40

In [21]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import regularizers

def train(X_train, y_train, activation_f, hidden, loss, opt):

    layers = [];

    layers.append(keras.layers.Dense(
            X_train.shape[1], 
            input_shape=(X_train.shape[1],),
            activation=activation_f,
            activity_regularizer=regularizers.l2(hidden[0][1])
        ))
    for i in hidden:
        layers.append(keras.layers.Dense(
            i[0],
            activation=activation_f,
            activity_regularizer=regularizers.l2(i[1])
        ))
    
    layers.append(keras.layers.Dense(
            1, 
            activation='sigmoid'
        ))
    model = keras.Sequential(layers)

    # opt = keras.optimizers.Adam(learning_rate=0.001) binary_crossentropy

    model.compile(optimizer=opt,
                  loss=loss,
                  metrics=['accuracy', 'Precision', 'Recall'])

    model.fit(X_train, y_train, epochs=50,verbose=0)
    
    return model

In [14]:
def evaluate(model, X_test, y_test):
    model.evaluate(X_test, y_test)

In [15]:
def prediction(model, X_test):
    yp = model.predict(X_test)
    y_pred = []
    for element in yp:
        if element > 0.5:
            y_pred.append(1)
        else:
            y_pred.append(0)
            
    return y_pred

In [16]:
from sklearn.metrics import confusion_matrix , classification_report

def report(y_test, y_pred):
    print(classification_report(y_test,y_pred))

In [17]:
from sklearn.metrics import f1_score
def f1score(y_test, y_pred):
    f1 = f1_score(y_test, y_pred)
    # print(f1)
    return f1

In [18]:
def modelF1(X_train, y_train, X_test, y_test, activation_f, hidden, loss, opt):
    # print(' ------------ Training --------------')
    model = train(X_train, y_train, activation_f, hidden, loss, opt)
    # print(' ------------ Evaluation --------------')
    # evaluate(model, X_test, y_test)
    # print(' ------------ Prediction --------------')
    y_pred = prediction(model, X_test)
    # print(' ------------ Report --------------')
#     report(y_test, y_pred)
    # print(' ------------ F1-Score --------------')
    return f1score(y_test, y_pred)

In [32]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

activation_f = ['relu']
hidden =[[[3,0]], [[4,0]], [[5,0]], [[6,0]], [[7,0]], [[8,0]], [[13,0], [5,0]], [[12,0], [4,0]], [[11,0], [4,0]], [[11,0], [3,0]], [[10,0], [3,0]]]

loss = ['binary_crossentropy', 'mean_squared_error']

lr_schedule = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=1e-1,
    decay_steps=10000,
    decay_rate=0.9)

opt = [keras.optimizers.Adam(learning_rate=lr_schedule), keras.optimizers.SGD(learning_rate=lr_schedule)]
maxf1 = 0
maxf1_config = ''

for i in range(44):
    f1_total = 0
    print(f'Iteration - {i + 1}/44')
    for train_index, test_index in folds.split(X, y):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        f1_total = f1_total + modelF1(X_train, y_train, X_test, y_test, activation_f[0], hidden[i % 11], loss[(i//11) % 2], opt[(i//22) % 2])

    f1_avg = f1_total / 5
    print(f'F1: {f1_avg} - Activation function: {activation_f[0]}, hidden layers: {len(hidden[i % 11])}, hidden: {hidden[i % 11]}, loss: {loss[(i//11) % 2]}, opt: {(i//22) % 2}')
    if(f1_avg > maxf1):
        print("---- MAX changed -----")
        maxf1 = f1_avg
        maxf1_config = f'Activation function: {activation_f[0]}, hidden layers: {len(hidden[i % 11])}, hidden: {hidden[i % 11]}, loss: {loss[(i//11) % 2]}, opt: {(i//22) % 2}'

print(f'--------- F1 - {maxf1}, Configuration - {maxf1_config}')

Iteration - 1/44
F1: 0.0 - Activation function: relu, hidden layers: 1, hidden: [[3]], loss: binary_crossentropy, opt: 0
Iteration - 2/44
F1: 0.19344262295081965 - Activation function: relu, hidden layers: 1, hidden: [[4]], loss: binary_crossentropy, opt: 0
---- MAX changed -----
Iteration - 3/44
F1: 0.0 - Activation function: relu, hidden layers: 1, hidden: [[5]], loss: binary_crossentropy, opt: 0
Iteration - 4/44
F1: 0.1315068493150685 - Activation function: relu, hidden layers: 1, hidden: [[6]], loss: binary_crossentropy, opt: 0
Iteration - 5/44
F1: 0.12817679558011047 - Activation function: relu, hidden layers: 1, hidden: [[7]], loss: binary_crossentropy, opt: 0
Iteration - 6/44
F1: 0.43462615453968134 - Activation function: relu, hidden layers: 1, hidden: [[8]], loss: binary_crossentropy, opt: 0
---- MAX changed -----
Iteration - 7/44
F1: 0.0 - Activation function: relu, hidden layers: 2, hidden: [[13], [5]], loss: binary_crossentropy, opt: 0
Iteration - 8/44
F1: 0.0 - Activation function: relu, hidden layers: 2, hidden: [[12], [4]], loss: binary_crossentropy, opt: 0
Iteration - 9/44
F1: 0.0 - Activation function: relu, hidden layers: 2, hidden: [[11], [4]], loss: binary_crossentropy, opt: 0
Iteration - 10/44
F1: 0.0 - Activation function: relu, hidden layers: 2, hidden: [[11], [3]], loss: binary_crossentropy, opt: 0
Iteration - 11/44
F1: 0.0 - Activation function: relu, hidden layers: 2, hidden: [[10], [3]], loss: binary_crossentropy, opt: 0
Iteration - 12/44
F1: 0.33944182490123614 - Activation function: relu, hidden layers: 1, hidden: [[3]], loss: mean_squared_error, opt: 0
Iteration - 13/44
F1: 0.19666666666666666 - Activation function: relu, hidden layers: 1, hidden: [[4]], loss: mean_squared_error, opt: 0
Iteration - 14/44
F1: 0.4391479137365213 - Activation function: relu, hidden layers: 1, hidden: [[5]], loss: mean_squared_error, opt: 0
---- MAX changed -----
Iteration - 15/44
F1: 0.0 - Activation function: relu, hidden layers: 1, hidden: [[6]], loss: mean_squared_error, opt: 0
Iteration - 16/44
F1: 0.8369884954502217 - Activation function: relu, hidden layers: 1, hidden: [[7]], loss: mean_squared_error, opt: 0
---- MAX changed -----
Iteration - 17/44
F1: 0.7882037354678865 - Activation function: relu, hidden layers: 1, hidden: [[8]], loss: mean_squared_error, opt: 0
Iteration - 18/44
F1: 0.15338345864661657 - Activation function: relu, hidden layers: 2, hidden: [[13], [5]], loss: mean_squared_error, opt: 0
Iteration - 19/44
F1: 0.125 - Activation function: relu, hidden layers: 2, hidden: [[12], [4]], loss: mean_squared_error, opt: 0
Iteration - 20/44
F1: 0.3171171171171171 - Activation function: relu, hidden layers: 2, hidden: [[11], [4]], loss: mean_squared_error, opt: 0
Iteration - 21/44
F1: 0.2758234295415959 - Activation function: relu, hidden layers: 2, hidden: [[11], [3]], loss: mean_squared_error, opt: 0
Iteration - 22/44
F1: 0.0 - Activation function: relu, hidden layers: 2, hidden: [[10], [3]], loss: mean_squared_error, opt: 0
Iteration - 23/44
F1: 0.8361549684349212 - Activation function: relu, hidden layers: 1, hidden: [[3]], loss: binary_crossentropy, opt: 1
Iteration - 24/44
F1: 0.84201934230795 - Activation function: relu, hidden layers: 1, hidden: [[4]], loss: binary_crossentropy, opt: 1
---- MAX changed -----
Iteration - 25/44
F1: 0.8382434617179324 - Activation function: relu, hidden layers: 1, hidden: [[5]], loss: binary_crossentropy, opt: 1
Iteration - 26/44
F1: 0.8343004327200045 - Activation function: relu, hidden layers: 1, hidden: [[6]], loss: binary_crossentropy, opt: 1
Iteration - 27/44
F1: 0.8259483206851629 - Activation function: relu, hidden layers: 1, hidden: [[7]], loss: binary_crossentropy, opt: 1
Iteration - 28/44
F1: 0.8470265435585107 - Activation function: relu, hidden layers: 1, hidden: [[8]], loss: binary_crossentropy, opt: 1
---- MAX changed -----
Iteration - 29/44
F1: 0.8544151026503968 - Activation function: relu, hidden layers: 2, hidden: [[13], [5]], loss: binary_crossentropy, opt: 1
---- MAX changed -----
Iteration - 30/44
F1: 0.83925983522223 - Activation function: relu, hidden layers: 2, hidden: [[12], [4]], loss: binary_crossentropy, opt: 1
Iteration - 31/44
F1: 0.8095742908598217 - Activation function: relu, hidden layers: 2, hidden: [[11], [4]], loss: binary_crossentropy, opt: 1
Iteration - 32/44
F1: 0.8006102997463387 - Activation function: relu, hidden layers: 2, hidden: [[11], [3]], loss: binary_crossentropy, opt: 1
Iteration - 33/44
F1: 0.8532825041169072 - Activation function: relu, hidden layers: 2, hidden: [[10], [3]], loss: binary_crossentropy, opt: 1
Iteration - 34/44
F1: 0.8457217858638286 - Activation function: relu, hidden layers: 1, hidden: [[3]], loss: mean_squared_error, opt: 1
Iteration - 35/44
F1: 0.8531730661363334 - Activation function: relu, hidden layers: 1, hidden: [[4]], loss: mean_squared_error, opt: 1
Iteration - 36/44
F1: 0.8496879113170097 - Activation function: relu, hidden layers: 1, hidden: [[5]], loss: mean_squared_error, opt: 1
Iteration - 37/44
F1: 0.857108404461002 - Activation function: relu, hidden layers: 1, hidden: [[6]], loss: mean_squared_error, opt: 1
---- MAX changed -----
Iteration - 38/44
F1: 0.8520610778905195 - Activation function: relu, hidden layers: 1, hidden: [[7]], loss: mean_squared_error, opt: 1
Iteration - 39/44
F1: 0.8532306092501644 - Activation function: relu, hidden layers: 1, hidden: [[8]], loss: mean_squared_error, opt: 1
Iteration - 40/44
F1: 0.8496109041697795 - Activation function: relu, hidden layers: 2, hidden: [[13], [5]], loss: mean_squared_error, opt: 1
Iteration - 41/44
F1: 0.8591411532259603 - Activation function: relu, hidden layers: 2, hidden: [[12], [4]], loss: mean_squared_error, opt: 1
---- MAX changed -----
Iteration - 42/44
F1: 0.8556361645432501 - Activation function: relu, hidden layers: 2, hidden: [[11], [4]], loss: mean_squared_error, opt: 1
Iteration - 43/44
F1: 0.8561750391407725 - Activation function: relu, hidden layers: 2, hidden: [[11], [3]], loss: mean_squared_error, opt: 1
Iteration - 44/44
F1: 0.8585582579395827 - Activation function: relu, hidden layers: 2, hidden: [[10], [3]], loss: mean_squared_error, opt: 1
--------- F1 - 0.8591411532259603, Configuration - Activation function: relu, hidden layers: 2, hidden: [[12], [4]], loss: mean_squared_error, opt: 1

In [24]:
maxf1

0.8569803339397868

In [34]:
hidden_with_loss = [[[12, 1e-2], [4, 1e-2]], [[12, 1e-1], [4, 1e-1]], [[12, 1e-3], [4, 1e-3]], [[12, 1e-2], [4, 1e-1]], [[12, 1e-3], [4, 1e-2]], [[12, 1e-2], [4, 1e-3]], [[12, 1e-4], [4, 1e-2]], [[12, 1e-1], [4, 1e-2]]]

maxf1 = 0
maxf1_config = ''

for i in range(len(hidden_with_loss)):
    f1_total = 0
    print(f'Iteration - {i + 1}/{len(hidden_with_loss)}')
    for train_index, test_index in folds.split(X, y):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        f1_total = f1_total + modelF1(X_train, y_train, X_test, y_test, activation_f[0], hidden_with_loss[i], loss[1], opt[1])

    f1_avg = f1_total / 5
    print(f'F1: {f1_avg} - hidden: {hidden_with_loss[i]}')
    if(f1_avg > maxf1):
        print("---- MAX changed -----")
        maxf1 = f1_avg
        maxf1_config = f'hidden: {hidden_with_loss[i]}'

print(f'--------- F1 - {maxf1}, Configuration - {maxf1_config}')

Iteration - 1/8
F1: 0.847046143875714 - hidden: [[12, 0.01], [4, 0.01]]
---- MAX changed -----
Iteration - 2/8
F1: 0.8306896568633968 - hidden: [[12, 0.1], [4, 0.1]]
Iteration - 3/8
F1: 0.6575605683554426 - hidden: [[12, 0.001], [4, 0.001]]
Iteration - 4/8
F1: 0.8620026921373446 - hidden: [[12, 0.01], [4, 0.1]]
---- MAX changed -----
Iteration - 5/8
F1: 0.8555151560157193 - hidden: [[12, 0.001], [4, 0.01]]
Iteration - 6/8
F1: 0.8540309389473197 - hidden: [[12, 0.01], [4, 0.001]]
Iteration - 7/8
F1: 0.789411655666942 - hidden: [[12, 0.0001], [4, 0.01]]
Iteration - 8/8
F1: 0.8173149421707799 - hidden: [[12, 0.1], [4, 0.01]]
--------- F1 - 0.8620026921373446, Configuration - hidden: [[12, 0.01], [4, 0.1]]